# SYSTEM #

system:
  cookie: 1000 * 60 * 5
  host: http://localhost
  port: 8080
  websocket: ws://localhost
  tunnel:
    enable: false
  log:
    console: true
    persist: false

# INTEGRATIONS #

integration:
  auth0:
    host: https://beehappydev.us.auth0.com/api/v2/
    pass: noybo0dKQtflkVr_IzA6WGDUZ15jGqLrih-EqS69wrq2mVD5kQj_UNgRiOQpHRxX
    user: 7QMq4WvuXvz9Yzomz4yfUaHATM4ElAUR
  discord:
    beebee:
      notifications: https://discord.com/api/webhooks/1043051348381421598/oqytOEnH2Ms4cnVaOD5Q1_XDP-JysOCy1ArLC3fYGA1JZ8x3RkRXalCB3BdCJKNACefc
    beejay:
      inspirational: https://discord.com/api/webhooks/1054319461982797864/ruSL9Op3HJwxFII5FWqZP3IGdLEIq0SU2jaxiKimufCH5DcVal4wlV-mMNYUrywg0F3y
      notifications: https://discord.com/api/webhooks/1043075407563472937/bE7TQvqC5qqTumO82UfY2yqZSTxAzRqSc7zWCBZiN6DlkBJsmB6XfNyvqxoc_Xsvx8HS
  filebase:
    bucket: sales
    endpoint: https://s3.filebase.com,
    pass: rI3iMJdb6HSzLTJhuwnAK9UxIY9NsmvdbRNvqh7x
    region: us-east-1
    user: 46457D476ADFE978450C
  mongo:
    datasource: BeeHappyCluster
    database: Development
    traces: dat_traces
    metrics: dat_metrics
    host: mongodb+srv://beehappydev:beehappydev@beehappycluster.2uqzs.mongodb.net/?retryWrites=true&w=majority&appName=BeeHappyCluster
  postgres:
    connections: 15
    database: postgres
    host: aws-0-us-west-1.pooler.supabase.com
    port: 6543
    pass: beehappydev
    user: postgres.kmvzmtoxdtnjjbhgfamt

# CHANNELS #

channel:
  messenger:
    enable: false
    token:
    secret:
    word:
  telegram:
    enable: false
    token: 6793157515:AAFm9a0HBko7Rze3hwFZJa6cxZ_PUmdOwms
    webhook: https://abacian.loca.lt
  whatsapp:
    enable: true

# SCHEDULERS #

scheduler:
  wakeup:
    cron: 0 0,10,20,30,40,50 * * * * UTC_OFFSET=0
    enable: true
    host: http://localhost:8080/backend/system/wakeup
    verbose: EVERY TEN MINUTES
  indicators:
    cron: 1 * * * * * UTC_OFFSET=0
    enable: false
    host: http://localhost:8080/backend/reload/indicators
    verbose: MANY TIMES PER DAY
  inspirational:
    cron: 1 * * * * * UTC_OFFSET=0
    enable: false
    host: http://localhost:8080/backend/load/inspirational
    verbose: ONE TIME PER DAY