# APPLICATION #

application:
  name: BeeHappy
  domain: .dev
  version: 4.1

# INTEGRATIONS #

integration:
  cloudflare:
    host: https://api.cloudflare.com/client/v4/zones/74ae119af953cb4a1446f3195b062c14/purge_cache
    token: Iw4yEBl68GmXxncUFK2jJgDjwXcs37bytPLrD5tv
  public: https://api64.ipify.org?format=json

# SCHEDULERS #

scheduler:
  wakeup:
    comment: Scheduled Wakeup task
  indicators:
    comment: Scheduled Indicators task
    host:
      dollar: https://api.cmfchile.cl/api-sbifv3/recursos_api/dolar
      euro: https://api.cmfchile.cl/api-sbifv3/recursos_api/euro
      foment_unit: https://api.cmfchile.cl/api-sbifv3/recursos_api/uf
      monthly_tax_unit: https://api.cmfchile.cl/api-sbifv3/recursos_api/utm
    token: f9c87a4ec0b0c3321c67eec16e1a427e92d8b06c
  inspirational:
    comment: Scheduled Inspirational task

stopWords:
  - a
  - ante
  - bajo
  - cabe
  - con
  - contra
  - de
  - desde
  - en
  - entre
  - hacia
  - hasta
  - para
  - por
  - segun
  - sin
  - sobre
  - tras
  - versus
  - el
  - la
  - los
  - las
  - del
  - un
  - una
  - unos
  - unas
  - hola
  - que
  - tal
  - por
  - favor
  - gracias
  - busco
  - quiero
  - necesito
  - deseo
  - puedo
  - como