# APPLICATION #

application:
  name: BeeHappy
  domain: .dev

# INTEGRATIONS #

integration:
  auth:
    suffix: user.beehappy.dev
  cloudflare:
    host: https://api.cloudflare.com/client/v4/zones/9cd5ceaf174e17679d4d11bc8dfe0fe6/purge_cache
    token: Xj717vFt8wVLISFbMkQySM40d7SjRBrfuburg-3o
  public: https://api64.ipify.org?format=json

# SCHEDULERS #

scheduler:
  wakeup:
    comment: BeeHappy.dev is running wakeup task
  indicators:
    comment: BeeHappy.dev is running indicators task
    host:
      dollar: https://api.cmfchile.cl/api-sbifv3/recursos_api/dolar
      euro: https://api.cmfchile.cl/api-sbifv3/recursos_api/euro
      foment_unit: https://api.cmfchile.cl/api-sbifv3/recursos_api/uf
      monthly_tax_unit: https://api.cmfchile.cl/api-sbifv3/recursos_api/utm
    token: f9c87a4ec0b0c3321c67eec16e1a427e92d8b06c
  inspirational:
    comment: BeeHappy.dev is running inspirational task